name: L'intégration continue
permissions: {}

on: pull_request

jobs:
  build:
    name: Construction du site

    runs-on: ubuntu-26.04

    steps:
      - name: Cloner le dépôt Git
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Installe Node.js, pnpm et les dépendances
        uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3.0.0
        with:
          require-lockfile: true
          node-version-file: '.nvmrc'

      - name: Vérfie le typage
        run: pnpm typecheck

      - name: Lint le projet
        run: pnpm lint

      - name: Exécute les tests
        run: pnpm test:ci
